Increase test default test coverage and clean setup script

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,36 +1,23 @@
-#!/usr/bin/env ruby
-require 'fileutils'
+#!/bin/sh
 
-# path to your application root.
-APP_ROOT = File.expand_path('..', __dir__)
+# Set up Rails app. Run this script immediately after cloning the codebase.
 
-def system!(*args)
-  system(*args) || abort("\n== Command #{args} failed ==")
-end
+# Exit if any subcommand fails
+set -e
 
-FileUtils.chdir APP_ROOT do
-  # This script is a way to setup or update your development environment automatically.
-  # This script is idempotent, so that you can run it at anytime and get an expectable outcome.
-  # Add necessary setup steps to this file.
+# Set up Ruby dependencies via Bundler
+gem install bundler --conservative
+bundle check || bundle install
 
-  puts '== Installing dependencies =='
-  system! 'gem install bundler --conservative'
-  system('bundle check') || system!('bundle install')
+# Install JavaScript dependencies
+bin/yarn
 
-  # Install JavaScript dependencies
-  # system('bin/yarn')
+# Set up database and add any development seed data
+bin/rails dev:prime
 
-  # puts "\n== Copying sample files =="
-  # unless File.exist?('config/database.yml')
-  #   FileUtils.cp 'config/database.yml.sample', 'config/database.yml'
-  # end
-
-  puts "\n== Preparing database =="
-  system! 'bin/rails db:prepare'
-
-  puts "\n== Removing old logs and tempfiles =="
-  system! 'bin/rails log:clear tmp:clear'
-
-  puts "\n== Restarting application server =="
-  system! 'bin/rails restart'
-end
+if [ ! -d .git/safe ] && echo $PATH | grep .git/safe > /dev/null; then
+  echo "-----------------------------------------------------------------------"
+  echo
+  echo "-> When you trust this repo, remember to run: mkdir -p .git/safe"
+  echo
+fi
